[project]
name = "pokedex-scraper-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markdownify>=1.1.0",
    "pymilvus>=2.5.3",
    "pyyaml>=6.0.2",
    "scrapy>=2.13.3",
]
